# Generated by Django 6.0.1 on 2026-02-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantName', models.CharField(max_length=100, unique=True)),
                ('RestaurantPlace', models.CharField(max_length=100)),
                ('RestDescription', models.TextField()),
                ('RestaurantImage', models.ImageField(upload_to='restaurants')),
            ],
        ),
    ]
