# Generated by Django 6.0.1 on 2026-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_restaurantdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=100)),
                ('Category_Name', models.CharField(max_length=100)),
                ('Restaurant_Name', models.CharField(max_length=100)),
                ('DishPrice', models.IntegerField(default=0)),
                ('DishDescription', models.TextField()),
                ('DishImage', models.ImageField(upload_to='dishes')),
            ],
        ),
    ]
