# Generated by Django 6.0.1 on 2026-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_dishdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishdb',
            name='DishPrice',
            field=models.IntegerField(),
        ),
    ]
