# Generated by Django 6.0.1 on 2026-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_dishdb_dishprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishdb',
            name='DishPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
