# Generated by Django 6.0.1 on 2026-02-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_userdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDb',
            new_name='RegistrationDb',
        ),
    ]
