# Generated by Django 6.0.1 on 2026-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_rename_userdb_registrationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Dish_Name', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Total_Price', models.FloatField()),
                ('Dish_Image', models.ImageField(blank=True, null=True, upload_to='Cart Images')),
            ],
        ),
    ]
