# Generated by Django 6.0.1 on 2026-02-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Restaurant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
