# Generated by Django 6.0.1 on 2026-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_orderdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='GrandTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
